In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sko.GA import GA
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
 
#首先学习一下官方文档
 
'''
min f(x1, x2, x3) = x1^2 + x2^2 + x3^2
s.t.
    x1*x2 >= 1
    x1*x2 <= 5
    x2 + x3 = 1
    0 <= x1, x2, x3 <= 5
'''
def obj_func(p):
    print(p)
    x1, x2, x3 = p
    return x1 ** 2 + x2 ** 2 + x3 ** 2
 
constraint_eq = [
    #等式约束条件：
    lambda x: 1 - x[1] - x[2]
]
 
constraint_ueq = [
    #不等式约束条件：
    lambda x: 1 - x[0] * x[1],
    lambda x: x[0] * x[1] - 5
    #无需使用不等式表示，直接使用表达式即可，但该表达式需要小于等于0，列如第一个约束条件5>=x1*x2,则改写成x1*x2-5：
]
 
 
 
ga = GA(func=obj_func,n_dim=3,size_pop=50,max_iter=100,lb=[0,0,0],ub=[5,5,5],constraint_eq = constraint_eq,constraint_ueq=constraint_ueq,precision=[1,0.1,0.01])
#func：需要优化的目标，n_dim:优化参数个数，lb、ub参数的上下界,constraint_eq、constraint_ueq：约束条件，
# precision：可以使用整数或浮点数，若使用整数例如1则自变量会启用整数规划模式，浮点数同理，但是优化结果得到的整数是带有小数点的（1.0000），在有些情况下比如random_state他的值必须是个整数，此时需要将结果转成整型
best_x,best_y = ga.run()
print('best_x:', best_x,'\n','best_y:',best_y)
 
#网上大部分例子都是和官方给出的差不多，我尝试使用该包来优化skearn中的逻辑回归模型，该例子比较简单
 
iris = load_iris()
xtrain,xtest,ytrain,ytest = train_test_split(iris['data'],iris['target'],test_size=0.2)
def func(p):
    w1, w2 = p
    clf = LogisticRegression(max_iter=int(w1), random_state=int(w2))
    clf.fit(xtrain,ytrain)
    score = clf.score(xtest,ytest)
    return -score #由于这里的GA默认求得最小值，而我们想要score达到最大值，因此需要在score前加负号
 
ga = GA(func=func, n_dim=2, size_pop=50, max_iter=10, lb=[0, 0],ub=[5, 10],precision=1)
best_x,best_y = ga.run()
print('best_x:', best_x,'\n','best_y:',best_y)
 

[5.         3.65079365 1.95694716]
[0.         3.65079365 4.71624266]
[0.         0.87301587 3.26810176]
[5.         1.9047619  0.99804305]
[3.         0.07936508 0.6555773 ]
[4.         0.79365079 3.58121331]
[1.         1.58730159 0.518591  ]
[5.         4.76190476 1.12524462]
[5.         0.79365079 4.8630137 ]
[2.         2.22222222 1.74168297]
[4.         2.53968254 4.3444227 ]
[2.         1.03174603 4.54011742]
[1.         2.3015873  4.30528376]
[3.         2.46031746 3.84540117]
[5.         3.33333333 3.13111546]
[4.         3.33333333 3.20939335]
[5.         3.33333333 0.96868885]
[1.         2.6984127  2.29941292]
[5.         2.22222222 3.33659491]
[5.         3.80952381 3.3072407 ]
[4.         3.57142857 1.29158513]
[4.         2.22222222 0.80234834]
[4.         2.3015873  1.48727984]
[2.         0.95238095 1.1741683 ]
[3.         0.23809524 3.64970646]
[0.         4.20634921 1.54598826]
[5.         2.3015873  4.36399217]
[4.         0.79365079 2.20156556]
[0.         4.126984

/home/zhangmanman/anaconda3/envs/XgboostENV/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/home/zhangmanman/anaconda3/envs/XgboostENV/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scik

best_x: [3. 4.] 
 best_y: [-0.96666667]


/home/zhangmanman/anaconda3/envs/XgboostENV/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/home/zhangmanman/anaconda3/envs/XgboostENV/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scik