#### Bellman Equation :贝尔曼公式
* #### 核心概念[core concept]:状态值[state value]:
* #### 基本工具[fundamental tool]:贝尔曼公式[Bellman equation] 

#### 本次课程大纲
* #### 1.0  一些例子
* #### 2.0  状态值
* #### 3.0  贝尔曼公式:推导
* #### 4.0  贝尔曼公式:矩阵形式
* #### 5.0  贝尔曼公式:求解状态值
* #### 6.0  动作值
* #### 7.0  总和
![](./images/3贝尔曼公式解决什么问题.png)
以上三种策略直观上可以看出第一个策略最优，第二个策略最差，第三个策略不好也不差，但是如何在数学上表达呢
![](./images/3return的gamma计算推导策略一.png)

策略一的计算过程
下面是以上式子的python计算证明 

In [33]:
import numpy as np

gamma = np.random.uniform(0,1)
print(f'gamma:{gamma}')
n = 10
point = 0
gammas = np.zeros(n)
gammas_sum = np.zeros(n)
for i in range(n):
    if i == point:
        gammas_sum[i] = 0
    else:
        gammas_sum[i] = gamma ** i
    gammas[i] = gamma**i
(gamma*(gammas)).sum(),gamma/(1-gamma),gammas_sum.sum()

gamma:0.16296385702318295


(0.1946915389947429, 0.19469154156667817, 0.1946915257844347)

![3return的gamma计算推导策略二](./images/3return的gamma计算推导策略二.png)
以下是上式策略二的python的证明

In [67]:
import numpy as np

gamma = np.random.uniform(0,1)
print(f'gamma:{gamma}')
n = 10
point = 0
gammas = np.zeros(n)
Return = np.zeros(n)
discounterd_return = np.zeros(n)
point = 0

for i in range(n):
    if point >=i :
        Return[i] = -1
    else:
        Return[i] = 1

for i in range(n):
    discounterd_return[i] = gamma**i*Return[i]
    if point <=i:
        gammas[i]=gamma**i

discounterd_return.sum(),(Return[:point+1]).sum()+(gamma*gammas[point:]).sum(),(Return[:point+1]).sum()+(gamma/(1-gamma))

gamma:0.28190034053536706


(-0.6074400432119189, -0.6074368739655239, -0.6074356298323089)

![](./images/3return的gamma计算推导策略三.png)
第三个策略的结果是一二策略的分别乘以概率0.5,以下是对上面的等式python的计算证明，严格意义上第三个策略求出的是期望而不是返回值了，其实就是state value状态值了

In [72]:
step0 = 0.5*(-1+(gamma/(1-gamma))) + 0.5*(gamma/(1-gamma))
step1 = 0.5*-1+0.5*(gamma/(1-gamma))+0.5*(gamma/(1-gamma))
step2 = 0.5*(-1+ (gamma/(1-gamma))*2)
step3 = 0.5 * -1 + 0.5*2*(gamma/(1-gamma))
step4 = -0.5 + 1*(gamma/(1-gamma))
step5 = -0.5+(gamma/(1-gamma))
for i, step in enumerate((step0,step1,step2,step3,step4,step5)):
    print(f"第{i}步证明计算值为:{step}")

第0步证明计算值为:-0.10743562983230895
第1步证明计算值为:-0.10743562983230895
第2步证明计算值为:-0.10743562983230898
第3步证明计算值为:-0.10743562983230898
第4步证明计算值为:-0.10743562983230898
第5步证明计算值为:-0.10743562983230898


![](./images/3return的gamma计算推导策略四.png)
#### 直观上就可以看出来不同策略比较结果:
* ##### 策略1：$ \gamma/(1-\gamma) $
* ##### 策略2：$ -1+(\gamma/(1-\gamma))$
* ##### 策略3：$ -0.5 + (\gamma/(1-\gamma)) $
以下再用python计算以下结果观察

In [76]:
gammas = np.random.uniform(0,1,10)


def policy1(gamma):
    return gamma/(1-gamma)
def policy2(gamma):
    return -1+gamma/(1-gamma)
def policy3(gamma):
    return -0.5+gamma/(1-gamma)
for gamma in gammas:
    print(f"gamma{gamma},策略一:{policy1(gamma)},策略二:{policy2(gamma)},策略三:{policy3(gamma)}")


gamma0.8255390865686738,策略一:4.731942933989248,策略二:3.731942933989248,策略三:4.231942933989248
gamma0.7100311447325648,策略一:2.4486462316020474,策略二:1.4486462316020474,策略三:1.9486462316020474
gamma0.5168742520494072,策略一:1.069854492835405,策略二:0.06985449283540501,策略三:0.569854492835405
gamma0.1499587734254233,策略一:0.1764135299998499,策略二:-0.8235864700001501,策略三:-0.32358647000015006
gamma0.7989347452754809,策略一:3.973509726332911,策略二:2.973509726332911,策略三:3.473509726332911
gamma0.1882567258261273,策略一:0.2319165822688459,策略二:-0.7680834177311541,策略三:-0.2680834177311541
gamma0.7242417644553701,策略一:2.626364949808202,策略二:1.626364949808202,策略三:2.126364949808202
gamma0.7572360971044958,策略一:3.1192285511674362,策略二:2.1192285511674362,策略三:2.6192285511674362
gamma0.37931045037221445,策略一:0.611111385071134,策略二:-0.38888861492886595,策略三:0.11111138507113405
gamma0.1736708995916918,策略一:0.21017158842146189,策略二:-0.7898284115785381,策略三:-0.2898284115785381


#### 通过上面可以看出Return/返回值可以用来衡量策略的好坏
#### 那如何计算return？
![](./images/3如何计算return1.png)
#### 另一种计算方式
![](./images/3如何计算return12.png)
#### Bootstrapping/自举
* #### 以上我们通过对第一种方法的约简，得到的四步就变得非常简单，在强化学习中被称为Bootstrapping/自举
#### 自举的计算方法
![](./images/3自举的计算方法.png)
#### 求解上面的式子
* #### $ v = r+(\gamma P v)$
* #### $ (I-\gamma p )v = r $
* #### $ v = (I-\gamma p )^{-1}r  $
* #### $ 以上 I是单位矩阵，(I-\gamma p )^{-1}是对(I-\gamma p )求逆运算 $\
以下是python的计算验证

In [26]:
import numpy as np
n = 4
I = np.identity(n)
print(f"I:{I}")

gamma = np.random.uniform(0,1)
gamma

P = np.random.random_integers(0,1,size=n*n).reshape((n,n))
print(f"P:{P}")
r = np.random.normal(0,1,n)
print(f"r:{r}")

v = np.linalg.inv(I-gamma*P).dot(r)
v

I:[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
P:[[0 0 1 0]
 [1 0 0 1]
 [0 0 0 1]
 [1 0 0 1]]
r:[-0.0500688   0.3290625   0.7163425   0.29093356]


/home/zhangmanman/anaconda3/envs/XGBoostAndScikitOPT_GPU/lib/python3.7/site-packages/ipykernel_launcher.py:9: DeprecationWarning: This function is deprecated. Please call randint(0, 1 + 1) instead
  if __name__ == "__main__":


array([0.68188104, 1.37751428, 1.41109553, 1.33938534])

In [27]:
v = r+(gamma*P.dot(v))
v

array([0.68188104, 1.37751428, 1.41109553, 1.33938534])

![](./images/3列出示例的贝尔曼方程.png)

#### 以下是python的计算验证
#### 先将上面的贝尔曼公式转成线性方程组
* #### step-1
* * ##### $0 = v_{1} - \gamma v_{3}$
* * ##### $1 = v_{2} - \gamma v_{4}$
* * ##### $1 = v_{3} - \gamma v_{4}$
* * ##### $1 = v_{4} - \gamma v_{4}$
* #### step-2
* * ##### $0 = 1 v_{1}  + 0 v_{2} - 1 \gamma v_{3} + 0 v_{4}$
* * ##### $1 = 0 v_{1}  + 1 v_{2} + 0 v_{3} - 1 \gamma v_{4}$
* * ##### $1 = 0 v_{1}  + 0 v_{2} + 1 v_{3} - 1 \gamma v_{4}$
* * ##### $1 = 0 v_{1}  + 0 v_{2} + 0 v_{3} + (1-\gamma) v_{4}$

In [45]:
import numpy as np

gamma = np.random.uniform(0,1)


a = np.array([0,1,1,1])
Matrix = np.array(
    [
        [1,0,-1*gamma,0]
        ,[0,1,0,-1*gamma]
        ,[0,0,1,-1*gamma]
        ,[0,0,0,(1-gamma)]
    ]
)
v = np.linalg.solve(Matrix,a)
v

array([0.95140621, 1.95140621, 1.95140621, 1.95140621])

##### 我们验证以下解是否正确

In [46]:
v[0]==0+gamma*v[2],v[1]==1+gamma*v[3]

(True, True)

In [48]:
import sympy
# gamma = np.random.uniform(0,1)

syMatrix = sympy.Matrix(
    [        
        [1,0,-1*gamma,0]
        ,[0,1,0,-1*gamma]
        ,[0,0,1,-1*gamma]
        ,[0,0,0,(1-gamma)]
    ]

)
sya = sympy.Matrix([0,1,1,1])
syMatrix.solve(sya)

Matrix([
[0.951406207872612],
[ 1.95140620787261],
[ 1.95140620787261],
[ 1.95140620787261]])