In [2]:
import numpy as np

X = np.random.normal(0,1,400).reshape(40,10)
X.shape

(40, 10)

## 参数设置默认
###### PCA(copy=True, iterated_power='auto', n_components=0.99, random_state=None,svd_solver='auto', tol=0.0, whiten=False)

In [3]:
from sklearn.decomposition import PCA  # 导入 sklearn.decomposition.PCA 类


modelPCA = PCA(n_components=2)  # 建立模型，设定保留主成分数 K=2
modelPCA.fit(X)  # 用数据集 X 训练 模型 modelPCA

PCA(n_components=2)

In [4]:
print(modelPCA.n_components_)  # 返回 PCA 模型保留的主成份个数

2


In [5]:
print(modelPCA.explained_variance_ratio_)  # 返回 PCA 模型各主成份占比

[0.19294641 0.18181607]


In [6]:
modelPCA.transform(X).shape

(40, 2)

#### 方差百分比建立模型

In [7]:
modelPCA2 = PCA(n_components=0.9) # 建立模型，设定主成份方差占比 0.9

In [8]:
Xtrans = modelPCA2.fit_transform(X)
Xtrans.shape

(40, 8)

#### 主成分方差贡献率

In [9]:
modelPCA2.explained_variance_ratio_ # 返回 PCA 模型各主成份占比

array([0.19294641, 0.18181607, 0.13630666, 0.10905516, 0.09694546,
       0.06893132, 0.06184328, 0.05911568])

#### 主成分方差

In [10]:
modelPCA2.explained_variance_ # * 降维后的各主成分的方差值。方差值越大，则说明越是重要的主成分。

array([1.87431655, 1.76619435, 1.32410775, 1.05938171, 0.94174581,
       0.66961139, 0.60075685, 0.57426051])

#### 主成分载荷矩阵

In [11]:
modelPCA2.components_

array([[ 0.61278887,  0.02705309,  0.11272518,  0.25531316,  0.02626036,
         0.29063204,  0.24338431, -0.11464445,  0.60645865, -0.14331159],
       [-0.05286742, -0.0738637 ,  0.32274864,  0.22454807, -0.36116824,
        -0.65166316,  0.01271264,  0.1713725 ,  0.34398622,  0.3663286 ],
       [-0.28092616,  0.06461298, -0.11579382,  0.16478364,  0.75013384,
        -0.12092767,  0.40883843,  0.00590856,  0.17129273,  0.32014769],
       [-0.11389442,  0.36480186,  0.23116809,  0.48235478, -0.18816223,
         0.48788343,  0.07466166,  0.33790805, -0.26203799,  0.32555714],
       [ 0.0856119 ,  0.58383104, -0.46505948,  0.03482258, -0.27917549,
        -0.17516511,  0.14438684, -0.5081309 , -0.04902728,  0.2103544 ],
       [ 0.60192753, -0.25999387, -0.39196464,  0.1557948 ,  0.07688139,
        -0.21429034,  0.08846738,  0.35090426, -0.41219277,  0.19870551],
       [-0.2311891 ,  0.21200944, -0.40349583, -0.03084846, -0.19852891,
        -0.07874826,  0.29711175,  0.57928534