In [24]:
import numpy as np

X = np.random.normal(0,1,4000).reshape(400,10)
X.shape

(400, 10)

In [27]:
X

array([[ 1.0252281 , -0.03895896,  0.1458192 , ...,  1.11075207,
        -0.14275553,  0.07332268],
       [-0.96084807, -1.54741314, -0.5620334 , ...,  0.23042889,
        -0.41026127, -0.8433077 ],
       [-0.49060147,  0.09432452,  0.44512869, ...,  0.64755628,
         1.06428733, -0.25667493],
       ...,
       [-0.16856119,  0.7978171 ,  0.35304063, ...,  0.4142003 ,
         1.54240205,  0.3666114 ],
       [-0.13168326,  0.79532405,  2.77679373, ..., -0.77499527,
         0.37822201,  1.21648183],
       [-1.54428854, -1.12331735,  1.34116209, ...,  1.64152917,
        -0.59795091,  0.9999024 ]])

In [28]:
#from factor_analyzer import factor_analyzer
from factor_analyzer import FactorAnalyzer

#### 选择适合的因子个数 

In [29]:
fa = FactorAnalyzer(n_factors=1
                    ,rotation="varimax"
                   ,method="principal"
                   ,use_smc=True)
fa.fit(X)

/home/zhangmanman/anaconda3/envs/XgboostENV/lib/python3.7/site-packages/factor_analyzer/factor_analyzer.py:664: UserWarning: No rotation will be performed when the number of factors equals 1.
  "No rotation will be performed when "


FactorAnalyzer(method='principal', n_factors=1, rotation='varimax',
               rotation_kwargs={})

#### 因子载荷矩阵

In [30]:
fa.loadings_

array([[ 0.40111514],
       [-0.07238059],
       [ 0.36789039],
       [-0.15004962],
       [-0.32249279],
       [ 0.06931135],
       [ 0.32243365],
       [ 0.61048685],
       [ 0.26519196],
       [ 0.51994109]])

#### 因各变量的共同度

In [31]:
fa.get_communalities()

array([0.16089336, 0.00523895, 0.13534334, 0.02251489, 0.1040016 ,
       0.00480406, 0.10396346, 0.3726942 , 0.07032677, 0.27033874])

#### 因子得分

In [32]:
import pandas as pd
data_newf = fa.transform(X)
scores_f = pd.DataFrame(data_newf,columns=[["因子"]])
scores_f

因子
0    0.805240
1   -0.941986
2    1.118653
3   -0.247853
4   -1.420424
..        ...
395 -0.106448
396 -0.715849
397  0.334770
398  0.491183
399  1.226172

[400 rows x 1 columns]